version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: react-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env

volumes:
  build_volume: